name: github-terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Sprawdź kod
        uses: actions/checkout@v2
      - name: Instalacja Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Inicjalizacja Terraform
        run: terraform init
      - name: Poprawność konfiguracji
        run: terraform plan
        env:
          TF_VAR_greeting: "Hello from Terraform!"
      - name: Tworzenie zasobów
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve
